// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxlF_Yd7Duw9-G4VKRqnomCUQvTYriNCQ',
    appId: '1:795940453759:web:a79dfaed77c80b28d76e4a',
    messagingSenderId: '795940453759',
    projectId: 'korlebu-appointments',
    authDomain: 'korlebu-appointments.firebaseapp.com',
    storageBucket: 'korlebu-appointments.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFTig-tR3B-dUBvYI2ANtc3BbAs88kITg',
    appId: '1:795940453759:android:67d4fbf7de9f9e2dd76e4a',
    messagingSenderId: '795940453759',
    projectId: 'korlebu-appointments',
    storageBucket: 'korlebu-appointments.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvUpHW9rQyKqqqlZ6i7U6Nb4X42wJD0IY',
    appId: '1:795940453759:ios:34491c598a609f0cd76e4a',
    messagingSenderId: '795940453759',
    projectId: 'korlebu-appointments',
    storageBucket: 'korlebu-appointments.firebasestorage.app',
    iosBundleId: 'com.example.korlebuAppointments',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvUpHW9rQyKqqqlZ6i7U6Nb4X42wJD0IY',
    appId: '1:795940453759:ios:34491c598a609f0cd76e4a',
    messagingSenderId: '795940453759',
    projectId: 'korlebu-appointments',
    storageBucket: 'korlebu-appointments.firebasestorage.app',
    iosBundleId: 'com.example.korlebuAppointments',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxlF_Yd7Duw9-G4VKRqnomCUQvTYriNCQ',
    appId: '1:795940453759:web:41a1a8eb2d684183d76e4a',
    messagingSenderId: '795940453759',
    projectId: 'korlebu-appointments',
    authDomain: 'korlebu-appointments.firebaseapp.com',
    storageBucket: 'korlebu-appointments.firebasestorage.app',
  );
}
